[[section-introduction-and-goals]]
== Introducción y Metas

Radarin es un sistema de geolocalización web/móvil descentralizado que pretende acercar a las personas a través de las nuevas tecnologías.

El sistema provee al cliente la facilidad de localizar por posicionamiento y cercanía a los amigos que tenga agregados en la aplicación (previa aceptación por parte del otro usuario). Cuando la aplicación detecte que un amigo del usuario está dentro de cierto margen, el sistema lanzará una notificación. 

Con esto, facilitamos el encuentro entre gente conocida priorizando la privacidad y la seguridad del sistema.

=== Vista de Requerimientos

Radarin contempla unos requisitos mínimos de funcionamiento que pretenden ser la base desde la cual se pueda ofrecer al cliente la funcionalidad descrita, además de servir para futuras ampliaciones.

==== Requisitos funcionales:
- Un usuario será capaz de ver qué otros usuarios conocidos tiene cerca.

- Un usuario podrá añadir a otros usuarios a su lista de amigos.

- El sistema ofrecerá al usuario notificaciones de amigos cerca.

- Cada cliente podrá gestionar y visualizar sus localizaciones.

- El administrador del servicio tendrá opción de gestionar usuarios y monitorizar el estado del servidor.

==== Requisitos no funcionales:
- Soporte completo con el proyecto SOLID.

- La aplicación estará alojada en un servidor web que únicamente almacenará localizaciones del usuario, con previa solicitud al mismo para acceder a la suya. 

- Toda información que no sea una localización será almacenada en el pod del usuario.

- El servicio debe ser soportado por los dispositivos móviles de los usuarios, tomando los datos de geolocalización provenientes del smartphone.

- El sistema se desplegará desde contenedores docker y utlizará el servicio en la nube heroku.

- La aplicación móvil tendrá un sistema de monitorización.

- Se deberá desarrollar pruebas unitarias, de aceptación y de carga para su ejecución automática en un servidor de integración continua.

=== Objetivos de Calidad

[options="header",cols="1,2"]
|===
|Objetivos|Motivación
| Seguridad de datos de los usuarios | _La aplicación mantendrá seguros los datos de los usuarios, tales como la localización utlizada al usar esta._
| Facilidad de uso | _Enfoque sencillo para poder ser utilizado por todo tipo de usuarios._
| Consistente | _La aplicación debe ser consistente._
| Eficiente | _La aplicación tendrá que ser eficiente, es decir, debe funcionar de forma fluida._
|===

=== Stakeholders

[options="header",cols="1,2,2"]
|===
|Rol/Nombre|Contacto|Expectativas
| Paulino Álvarez Ondina | Evaluará el resultado del trabajo del equipo de desarrollo.
 | _Aplicación bien desarrollada según los requerimentos pedidos._
| Equipo de desarrollo | Se encargará de desarrollar la aplicación. | _Aplicación funcional, fácil de usar, segura y siguiendo los principios SOLID._
| Usuarios | Usarán la aplicación de forma continuada | Poder enviar mensajes a otros usuarios cerca de su posición y que estén en su lista de amigos.
|===

