[[section-introduction-and-goals]]
== Introducción y Metas

Radarin es un sistema de geolocalización web/móvil descentralizado que pretende acercar a las personas a través de las nuevas tecnologías.

El sistema provee al cliente la facilidad de localizar por posicionamiento y cercanía a los amigos que tenga agregados en la aplicación (previa aceptación por parte del otro usuario). Cuando la aplicación detecte que un amigo del usuario está dentro de cierto margen, el sistema lanzará una notificación. 

Con esto, facilitamos el encuentro entre gente conocida priorizando la privacidad y la seguridad del sistema.

=== Vista de Requerimientos

Radarin contempla unos requisitos mínimos de funcionamiento que pretenden ser la base desde la cual se pueda ofrecer al cliente la funcionalidad descrita, además de servir para futuras ampliaciones.

==== Requisitos funcionales:
- Un usuario será capaz de ver qué otros usuarios conocidos tiene cerca.

- Un usuario podrá añadir a otros usuarios a su lista de amigos.

- El sistema ofrecerá al usuario notificaciones de amigos cerca.

- Cada cliente podrá gestionar y visualizar sus localizaciones.

- El administrador del servicio tendrá opción de gestionar usuarios y monitorizar el estado del servidor.

==== Requisitos no funcionales:
- Soporte completo con el proyecto SOLID.

- La aplicación estará alojada en un servidor web que únicamente almacenará localizaciones del usuario, con previa solicitud al mismo para acceder a la suya. 

- Toda información que no sea una localización será almacenada en el pod del usuario.

- El servicio debe ser soportado por los dispositivos móviles de los usuarios, tomando los datos de geolocalización provenientes del smartphone.

- El sistema se desplegará desde contenedores docker y utlizará el servicio en la nube heroku.

- La aplicación móvil tendrá un sistema de monitorización.

- Se deberá desarrollar pruebas unitarias, de aceptación y de carga para su ejecución automática en un servidor de integración continua.

=== Objetivos de Calidad
 

[options="header",cols="1,2"]
|===
|Objetivos|Escenarios
| Seguridad de datos de los usuarios | _La aplicación mantendrá segura los datos de los usuarios, tales como la localización utlizada al usar esta._
| Facilidad de uso | _prueba_
| Facilidad de uso | _prueba_
|===

[role="arc42help"]
****
.Contents
The top three (max five) quality goals for the architecture whose fulfillment is of highest importance to the major stakeholders. We really mean quality goals for the architecture. Don't confuse them with project goals. They are not necessarily identical.

.Motivation
You should know the quality goals of your most important stakeholders, since they will influence fundamental architectural decisions. Make sure to be very concrete about these qualities, avoid buzzwords.
If you as an architect do not know how the quality of your work will be judged …

.Form
A table with quality goals and concrete scenarios, ordered by priorities
****

=== Stakeholders

[role="arc42help"]
****
.Contents
Explicit overview of stakeholders of the system, i.e. all person, roles or organizations that

* should know the architecture
* have to be convinced of the architecture
* have to work with the architecture or with code
* need the documentation of the architecture for their work
* have to come up with decisions about the system or its development

.Motivation
You should know all parties involved in development of the system or affected by the system.
Otherwise, you may get nasty surprises later in the development process.
These stakeholders determine the extent and the level of detail of your work and its results.

.Form
Table with role names, person names, and their expectations with respect to the architecture and its documentation.
****

[options="header",cols="1,2,2"]
|===
|Role/Name|Contact|Expectations
| _<Role-1>_ | _<Contact-1>_ | _<Expectation-1>_
| _<Role-2>_ | _<Contact-2>_ | _<Expectation-2>_
|===
