[[section-introduction-and-goals]]
== Introducción y Metas

Radarin es un sistema de geolocalización web/móvil descentralizado que pretende acercar a las personas a través de las nuevas tecnologías.

El sistema provee al cliente la facilidad de localizar por posicionamiento y cercanía a los amigos que tenga agregados en la aplicación (previa aceptación por parte del otro usuario). Cuando la aplicación detecte que un amigo del usuario está dentro de un rango establecido por el usuario entre 1 y 30 kilómetros, el sistema lanzará una notificación. 

Con esto, facilitamos el encuentro entre gente conocida priorizando la privacidad y la seguridad del sistema.

=== Vista de Requerimientos

Radarin contempla unos requisitos mínimos de funcionamiento que pretenden ser la base desde la cual se pueda ofrecer al cliente la funcionalidad descrita, además de servir para futuras ampliaciones.

==== Requisitos funcionales:
- Un usuario será capaz de ver qué otros usuarios conocidos tiene cerca.

- Un usuario podrá añadir y eliminar a otros usuarios a su lista de amigos.

- El sistema ofrecerá al usuario notificaciones de amigos cercanos.

- El administrador del servicio tendrá opción de gestionar usuarios, pudiendo ver los usuarios del sistema, aquellos que estén activos (aquellos que hayan actualizado su ubicación en los últimos 15 minutos), así como banear, desbanear o eliminar usuarios del sistema y monitorizar el estado del servidor.

==== Requisitos no funcionales:
- Soporte con el proyecto SOLID.

- Utilización de Inrupt cómo proveedor por defecto para la gestión del POD desde la aplicación.

- La aplicación estará alojada en un servidor web que únicamente almacenará localizaciones del usuario con la marca de tiempo de la misma, con previa solicitud para acceder a la suya. 

- En el POD se almacenará el nombre del usuario, su foto de perfil, la lista de sus amigos y las notificaciones que se envíen al usuario.

- El servicio debe ser soportado por los dispositivos móviles de los usuarios, tomando los datos de geolocalización provenientes del smartphone.

- El sistema se desplegará desde contenedores docker y utlizará el servicio en la nube Heroku.

- Se deberá desarrollar pruebas unitarias, de aceptación y de carga para su ejecución automática en un servidor de integración continua.

=== Objetivos de Calidad

[options="header",cols="1,2"]
|===
|Objetivos|Motivación
| Seguridad de datos de los usuarios | _La aplicación mantendrá seguros los datos de los usuarios, tales como la localización utlizada al usar esta._
| Facilidad de uso | _Enfoque sencillo para poder ser utilizado por todo tipo de usuarios._
| Consistente | _La aplicación debe ser consistente._
| Eficiente | _La aplicación tendrá que ser eficiente, es decir, debe funcionar de forma fluida._
|===

=== Stakeholders

[options="header",cols="1,2,2"]
|===
|Rol/Nombre|Contacto|Expectativas
| Paulino Álvarez Ondina | Evaluará el resultado del trabajo del equipo de desarrollo.
 | _Aplicación bien desarrollada según los requerimentos pedidos._
| Equipo de desarrollo | Se encargará de desarrollar la aplicación. | _Aplicación funcional, fácil de usar, segura y siguiendo los principios SOLID._
| Usuarios | Usarán la aplicación de forma continuada | Poder enviar mensajes a otros usuarios cerca de su posición y que estén en su lista de amigos.
|===

