[[section-system-scope-and-context]]
== Alcance del sistema y Contexto

El alcance del proyecto a desarrollar abarca un sitio web/móvil en el que los usuarios podrán geolocalizar a sus amigos y viceversa. Haciendo uso de SOLID para asegurar la privacidad de cada usuario (con sus respectivos PODs).

La aplicación enviará un aviso cuando algún amigo se encuentre dentro de un determinado rango ("Tu amigo Pepito está a 1.7km de ti" ó "Tu amigo Pepito está a 10 minutos de ti")

Se podrán gestionar amigos (listar, agregar, borrar).

// Ampliable

=== Contexto empresarial 

El usuario puede guardar su información personal en su POD. El sistema podrá solamente acceder a su localización , pudiendo así la aplicación informar de los amigos que estén próximos.

* Usuario: guarda a los amigos y recibe su ubicación
* POD: registra los amigos, además de información personal del usuario
* Servidor: recibe la localización del usuario


=== Technical Context

[role="arc42help"]
****
.Contents
Technical interfaces (channels and transmission media) linking your system to its environment. In addition a mapping of domain specific input/output to the channels, i.e. an explanation with I/O uses which channel.

.Motivation
Many stakeholders make architectural decision based on the technical interfaces between the system and its context. Especially infrastructure or hardware designers decide these technical interfaces.

.Form
E.g. UML deployment diagram describing channels to neighboring systems,
together with a mapping table showing the relationships between channels and input/output.

****

**<Diagram or Table>**

**<optionally: Explanation of technical interfaces>**

**<Mapping Input/Output to Channels>**
