[[section-system-scope-and-context]]
== Alcance del sistema y Contexto

El alcance del proyecto a desarrollar abarca un sitio web/móvil en el que los usuarios podrán geolocalizar a sus amigos y viceversa. Haciendo uso de SOLID para asegurar la privacidad de cada usuario (con sus respectivos PODs).

La aplicación enviará un aviso cuando algún amigo se encuentre dentro de un determinado rango ("Tu amigo Pepito está a 1.7km de ti" ó "Tu amigo Pepito está a 10 minutos de ti")

Se podrán gestionar amigos (listar, agregar, borrar).

// Ampliable

=== Contexto empresarial 

El usuario puede guardar su información personal en su POD. El sistema podrá solamente acceder a su localización , pudiendo así la aplicación informar de los amigos que estén próximos.

* Usuario: guarda a los amigos y recibe su ubicación
* POD: registra los amigos, además de información personal del usuario
* Servidor: recibe la localización del usuario


=== Contexto Tecnológico

Para este proyecto vamos a usar algunas tecnologías como son el caso de SOLID o de REACT. 
La idea principal de nuestro proyecto es construir una aplicación que con la ayuda de alguna API de geolocalización
nos permita establecer una clase de red que nos permita almacenar con que personas estuvo en contacto la persona que posee
la aplicación, para realizar esto utilizamos SOLID para almacenar su localizacion y compartirla de forma segura.
Utilizaremos REACT para desarrollar tanto la aplicación web como la aplicación móvil, mientras que dejamos a SOLID la parte de la comunicación.
