[[section-solution-strategy]]
== Estrategia de solución

=== Decisiones tecnológicas
- Para construir esta aplicación, elegimos el lenguaje de programación *JavaScript*, ya que este es uno de los lenguajes más utilizados en la web y lo vemos adecuado para desarrollar aplicaciones solidas, dado que soporta módulos y es consistente con las aplicaciones web.

- Usamos *React*, una biblioteca de JavaScript para crear interfaces de usuario. La utilizamos porque tenemos ejemplos de otros años que nos sirven de guía y la vemos muy preparada para realizar trabajos en web.

- A su vez utilizamos *Android Studio* para poder hacer que nuestra aplicación se reproduzca a través de dispositivos móviles.

- También usamos *Node.js* para aprovechar el modelo entrada salida sin bloqueo y controlado por eventos, para seguir siendo liviano y eficiente frente a aplicaciones de uso de datos en tiempo real que se ejecutan en dispositivos.

- *Google Maps API* es la api que hemos escogido para realizar la parte de localización de la aplicación, ya que tenemos experiencia pasada con ella y la conocemos la mayoría.

- *LDFlex*: lo utilizamos para la comunicación entre usuarios mediante sus PODs.

- *Solid-auth-li*: utilizamos esta librería para poder añadir amigos al POD.

- *Sparql*: se trata de un lenguaje estandarizado para la consulta de grafos.

=== Metas de calidad

- *Usabilidad:* queremos que la aplicación sea sencilla de aprender a utilizar, hasta para alguien fuera del sector.

- *Testeabilidad*: se realizarán pruebas para garantizar la correcta funcionalidad de la aplicación.

- *Privacidad:* La aplicación solamente almacenará la localización del usuario cuando éste lo permita, y no guardará ninguna otra información del usuario.

=== Organización

- Se utiliza *Microsoft Teams*, una herramienta en línea para la reunión de los integrantes de un proyecto, asi como *Github* para el control de versiones del proyecto, el seguimiento de errores e incidencias, para la gestión operativa de proyectos y dejar constancia de las tareas a realizar por cada miembro del grupo con los *issues*. A demás, realizaremos reuniones semanales, sea una o varias para ir viendo el avance de cada uno.

