[[section-runtime-view]]
== Vistas en tiempo de ejecución



// [role="arc42help"]
// ****
// .Contents
// The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

// * important use cases or features: how do building blocks execute them?
// * interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
// * operation and administration: launch, start-up, stop
// * error and exception scenarios

// Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

// .Motivation
// You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
// You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

// .Form
// There are many notations for describing scenarios, e.g.

// * numbered list of steps (in natural language)
// * activity diagrams or flow charts
// * sequence diagrams
// * BPMN or EPCs (event process chains)
// * state machines
// * ...

// ****


En esta sección vamos a desarrollar la mayoría de las situaciones de tiempo de ejecución en las que se puede llegar a ver envuelta nuestra aplicación. 
Algún ejemplo de ello puede ser como se añade y se gestionan los amigos, o como se actualiza la ubicación dentro de la aplicación gracias a la API de geolocalización. 

=== Inicio de Sesión

* _El usuario ha de registrarse en la aplicación Radarín siguiendo unos pasos:_
1. El usuario abre la aplicación y accede a la pantalla de Inicio de Sesión/Registro.
2. El usuario usa sus credenciales para iniciar sesión.
3. Se comprueba que las credenciales sean correctas.
4. El servidor acepta/rechaza la petición de autenticación.

==== Aplicación Web
[plantuml,"inicio_de_sesion_web",png]
----
actor Pablo
participant  "Radarín"
participant "POD"
Pablo -> "Radarín": Envía solicitud para registrarse.
Pablo -> "POD": Introduce sus credenciales.
"POD" -> "POD": Verifica las credenciales.
"POD" -> "Radarín": acepta/rechaza la petición de autenticación.
----

==== Aplicación Móvil
[plantuml,"inicio_de_sesion_movil",png]
----
actor Pablo
participant "Radarín"
participant "Servidor"
participant "Base de Datos"
participant "POD"
participant "Caché"
Pablo -> "Radarín": Envía solicitud para registrarse.
"Radarín" -> "Servidor": Pide los datos del usuario.
"Servidor" -> "POD": Verifica las credenciales.
"POD" -> "Servidor": Devuelve los datos del POD.
"Servidor" -> "Caché": Comprueba si esos datos ya están guardados en la caché.
"Caché" -> "Servidor": Devuelve las credenciales si están guardadas.
"Servidor" -> "Base de Datos": Pide los datos necesarios de los amigos que devuelve el POD.
"Base de Datos" -> "Servidor": Devuelve los datos necesarios.
"Servidor" -> "Radarín": Devuelve todos los datos obtenidos.
----

=== Mis amigos
Nuestra aplicación permitirá que el usuario disponga de una lista de amigos dentro de la aplicación una vez se inicia sesión, de la misma manera permitiremos
la opción de añadir o eliminar amigos de la lista, la cual desembocará en una actualización de la página que nos permitirá ver los cambios.

==== Aplicación Web
[plantuml,"mostrar_amigos_web",png]
----
actor Pablo
participant "Radarín"
participant "POD"
Pablo -> "Radarín": Pide su lista de amigos
"Radarín" -> "POD": Consulta los amigos de ese usuario
"POD" -> "Radarín": Devuelve la lista de amigos de ese usuario
"Radarín" -> "Radarín": Muestra los amigos
----

==== Aplicación Móvil
[plantuml,"mostrar_amigos_movil",png]
----
actor Pablo
participant "Radarín"
participant "Servidor"
participant "POD"
participant "Caché"
Pablo -> "Radarín": Pide su lista de amigos
"Radarín" -> "Servidor": Consulta los amigos de ese usuario
"Servidor" -> "Caché": Consulta si ha cambiado los amigos de ese usuario
"Caché" -> "Servidor": Envía una respuesta.
"Servidor" -> "POD": Pide los amigos si ha habido cambios.
"POD" -> "Servidor": Devuelve la lista de amigos de ese usuario
"Servidor" -> "Radarín": Devuelve la lista de amigos de ese usuario
"Radarín" -> "Radarín": Muestra los amigos
----

=== Añadir nuevos amigos
Nuestra aplicación dispondrá de una opción para añadir amigos.

==== Aplicación Web y Móvil
[plantuml,"anadir_amigos_web_y_movil",png]
----
actor Pablo
participant "Radarín"
participant "Servidor"
participant "POD"
Pablo -> "Radarín": Pide añadir un amigo
"Radarín" -> "Servidor": Pide añadir el usuario a la lista de amigos
"Servidor" -> "POD": Pide añadir el usuario a la lista de amigos
"POD" -> "POD": Lo añade
"POD" -> "Radarín" : Devuelve los amigos de Pablo
"Radarín" -> "Radarín": Muestra los amigos
----

=== Eliminar amigos
Nuestra aplicación dispondrá de una opción para eliminar amigos.

==== Aplicación Web

[plantuml,"eliminar_amigos_web",png]
----
actor Pablo
participant "Radarín"
participant "Servidor"
participant "POD"
Pablo -> "Radarín": Pide eliminar un amigo
"Radarín" -> "Servidor": Pide eliminar el usuario a la lista de amigos
"Servidor" -> "POD": Pide eliminar el usuario a la lista de amigos
"POD" -> "POD": Lo elimina
"POD" -> "Radarín" : Devuelve los amigos de Pablo
"Radarín" -> "Radarín": Muestra los amigos
----

=== Compartir ubicación

Debemos poder permitir a la aplicación conocer nuestra ubicación.

==== Aplicación Web y Móvil

[plantuml,"compartir_ubicacion_web_y_movil",png]
----
actor Pablo
participant "Radarín"
participant "Servidor"
participant "Base de datos"
"Radarín" -> Pablo: Pide permiso para usar su localizacion
Pablo -> "Radarín": Concede permiso a su localización
"Radarín" -> "Servidor": envía la localización
"Servidor" -> "Base de datos": almacena la localización
----

=== Ver los amigos en el mapa

Vamos a poder ver a nuestros amigos en el mapa.

==== Aplicación Web

[plantuml,"ver_amigos_mapa_web",png]
----
actor Pablo
participant "Radarín"
participant "Servidor"
participant "Base de datos"
participant "POD"
"Radarín" -> "Servidor": pide las ubicaciones de los amigos cercanos
"Servidor" -> "POD": solicita la lista de amigos
"POD" -> "Servidor": devuelve la lista de amigos
"Servidor" -> "Base de datos": pide las localizaciones
"Base de datos" -> "Servidor": devuelve las localizaciones
"Servidor" -> "Radarín": envía la lista de localizaciones de amigos cercanos
"Radarín" -> "Pablo": notifica los amigos cercanos
----

==== Aplicación Móvil

Al hacer la carga de todos los datos en el Inicio de sesión, no es necesario realizar ninguna otra llamada.

[plantuml,"ver_amigos_mapa_movil",png]
----
actor Pablo
participant "Radarín"
"Radarín" -> "Radarín": lee la lista de localizaciones de amigos cercanos
"Radarín" -> "Pablo": notifica los amigos cercanos
----

=== Notificaciones

Nuestra aplicación dispondrá de un sistema de notificaciones que nos avise de las novedades que nos incumban dentro de la aplicación, entre estas novedades se encuentran notificaciones enviadas por nuestros amigos para quedar o para avisar de que son positivo en covid-19.

[plantuml,"ver_amigos_mapa",png]
----
actor Pablo
participant "Radarín"
participant "NotificationHelper"
participant "POD"
"NotificationHelper" -> "Radarín": crea un botón para mandar notificaciones
"Radarín" -> "NotificationHelper": al pulsar el botón manda una petición para crear la notificación
"NotificationHelper" -> "POD": crea la notificación y la añade en el pod del usuario al que se la enviamos
----