[[section-runtime-view]]
== Vistas en tiempo de ejecución



// [role="arc42help"]
// ****
// .Contents
// The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

// * important use cases or features: how do building blocks execute them?
// * interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
// * operation and administration: launch, start-up, stop
// * error and exception scenarios

// Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

// .Motivation
// You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
// You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

// .Form
// There are many notations for describing scenarios, e.g.

// * numbered list of steps (in natural language)
// * activity diagrams or flow charts
// * sequence diagrams
// * BPMN or EPCs (event process chains)
// * state machines
// * ...

// ****


En esta sección vamos a desarrollar la mayoría de las situaciones de tiempo de ejecución en las que se puede llegar a ver envuelta nuestra aplicación.
Algún ejemplo de ello puede ser como se añade y se gestionan los amigos, o como se actualiza la ubicación dentro de la aplicación gracias a la API de geolocalización.

=== Inicio de Sesión

* _El usuario ha de registrarse en la aplicación Radarín siguiendo unos pasos:_
1. El usuario abre la aplicación y accede a la pantalla de Inicio de Sesión/Registro.
2. El usuario usa sus credenciales para iniciar sesión.
3. Se comprueba que las credenciales sean correctas.
4. El servidor acepta/rechaza la petición de autenticación.

[plantuml,"inicio_de_sesion",png]
----
actor Pablo
participant  "Radarín"
participant "LoginManager"
participant "POD"
Pablo -> "Radarín": Envía solicitud para registrarse.
Pablo -> "LoginManager": Introduce sus credenciales
"LoginManager" -> "POD": Verifica las credenciales
"POD" -> "Radarín": acepta/rechaza la petición de autenticación.
----

=== Mis amigos
Nuestra aplicación permitirá que el usuario disponga de una lista de amigos dentro de la aplicación una vez se inicia sesión, de la misma manera permitiremos
la opción de añadir o eliminar amigos de la lista, la cual desembocará en una actualización de la página que nos permitirá ver los cambios.

[plantuml,"mostrar_amigos",png]
----
actor Pablo
participant  "Radarín"
participant "LDFlex"
Pablo -> "Radarín": Pide su lista de amigos
"Radarín" -> "LDFlex": Consulta los amigos de ese usuario
"LDFlex" -> "Radarín": Devuelve la lista de amigos de ese usuario
"Radarín" -> "Radarín": Muestra los amigos
----

=== Añadir nuevos amigos
Nuestra aplicación dispondrá de una opción para añadir amigos.

[plantuml,"anadir_amigos",png]
----
actor Pablo
participant  "Radarín"
participant "FriendsService"
participant "LDFlex"
Pablo -> "Radarín": Pide añadir un amigo
"Radarín" -> "FriendsService": Pide añadir un amigo
"FriendsService" -> "LDFlex": Pide añadir el usuario a la lista de amigos
"LDFlex" -> "LDFlex": Lo añade
"LDFlex" -> "Radarín" : Devuelve los amigos de Pablo
"Radarín" -> "Radarín": Muestra los amigos
----

=== Eliminar amigos
Nuestra aplicación dispondrá de una opción para eliminar amigos.

[plantuml,"eliminar_amigos",png]
----
actor Pablo
participant  "Radarín"
participant "FriendsService"
participant "LDFlex"
Pablo -> "Radarín": Pide eliminar un amigo
"Radarín" -> "FriendsService": Pide eliminar un amigo
"FriendsService" -> "LDFlex": Pide eliminar el usuario a la lista de amigos
"LDFlex" -> "LDFlex": Lo elimina
"LDFlex" -> "Radarín" : Devuelve los amigos de Pablo
"Radarín" -> "Radarín": Muestra los amigos
----

=== Compartir ubicación

Debemos poder permitir a la aplicación conocer nuestra ubicación.

[plantuml,"compartir_ubicacion",png]
----
actor Pablo
participant  "Radarín"
participant "API Localización"
participant "Base de datos"
"Radarín" -> Pablo: Pide permiso para usar su localizacion
Pablo -> "Radarín": Concede permiso a su localización
"Radarín" -> "API Localización": envía la localización
"Radarín" -> "Base de datos": almacena la localización
----

=== Ver los amigos en el mapa

Vamos a poder ver a nuestros amigos en el mapa.

[plantuml,"ver_amigos_mapa",png]
----
actor Pablo
participant  "Radarín"
participant "API Localización"
participant "LDFlex"
participant "Base de datos"
"Pablo" -> "Radarín": envía su ubicación
"Radarín" -> "LDFlex": solicita la lista de amigos
"LDFlex" -> "Radarín": devuelve la lista de amigos
"Radarín" -> "Base de datos": solicita la lista de localizaciones
"Base de datos" -> "Radarín": devuelve la lista de localizaciones
"Radarín" -> "API Localización": envia los amigos y las localizaciones
"API Localización" -> "API Localización": muestra los amigos en sus localizaciones
"Radarín" -> "Pablo": notifica dónde están sus amigos
----

=== Notificaciones
Nuestra aplicación dispondrá de un sistema de notificaciones que nos avise de las novedades que nos incumban dentro de la aplicación.
