[[section-runtime-view]]
== Vista de tiempo de ejecución


[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...

****

En esta sección vamos a desarrollar la mayoría de las situaciones de tiempo de ejecución en las que se puede llegar a ver envuelta nuestra aplicación.
Algún ejemplo de ello puede ser como se añade y se gestionan los amigos, o como se actualiza la ubicación dentro de la aplicación gracias a la API de geolocalización. 

=== Registrarse

* _El usuario ha de registrarse en la aplicación Radarín siguiendo unos pasos:_
1. El usuario abre la aplicación y accede a la pantalla de Inicio de Sesión/Registro.
2. El usuario usa sus credenciales para iniciar sesión.
3. Se comprueba que las credenciales sean correctas.
4. El servidor rechaza la petición de autenticación.
5. El servidor acepta la petición de autenticación.



=== Mis Amigos
Nuestra aplicación permitirá que el usuario disponga de una lista de amigos dentro de la aplicación una vez se inicia sesión, de la misma manera permitiremos
la opción de añadir o eliminar amigos de la lista, la cual desembocará en una actualización de la página que nos permitirá ver los cambios.

=== Añadir Nuevos Amigos
Nuestra aplicación dispondrá de una opción para añadir amigos.

=== Eliminar Amigos
Nuestra aplicación dispondrá de una opción para eliminar amigos.

=== ...

=== Notificaciones
Nuestra aplicación dispondrá de un sistema de notificaciones que nos avise de las novedades que nos incumban dentro de la aplicación.